### ISSUE TITLE
Unhandled exception when closing the application

### ISSUE THREAD

**Issue by senarvi** [nemethviktor/GeoTagNinja#108]
**Describe the bug**

When closing the application, an unhandled exception popped up. I'll see if I can reproduce it. Maybe this stack trace will help understand what happened:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.Exit(CancelEventArgs e)
   at GeoTagNinja.FrmMainApp.tmi_File_Quit_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I reckon you have some collection that is being modified while calling `Application.Exit()`. Unfortunately it's not clear what collection.

**Screenshots**
![Screenshot 2024-07-02 080022](https://github.com/nemethviktor/GeoTagNinja/assets/2337787/94b66867-26ac-48c4-b28f-32900ee6d951)

**Desktop:**
 - OS: Windows 11 Business (22H2)
 - Language: English (United States)
 - Country or region: Finland

**Comment by nemethviktor** [comment]
Thanks for that. I'm not quite sure at this point what precisely it may be as there are a few things that get cleaned up when exit() takes place and I haven't seen it to cause errors so far but if you manage to replicate it that might indeed help.

**Comment by nemethviktor** [comment]
I'll close this for now as I can't seem to replicate it but if comes up again, shout ;)
