### ISSUE TITLE
Program hangs in the start

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#51]
I get an error of invalid date format. If I Ignore the JIT error message, the reading dates window remains visible and nothing happens, if I select Quit, the program aborts.

My date format is
hh.mm DD/MM/YYYY

What I can do to pinpoint the issue?

```
************** Exception Text **************
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at GeoTagNinja.HelperStatic.<ExifGetExifFromFolder>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GeoTagNinja.FrmMainApp.<lvwFileList_LoadOrUpdate>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GeoTagNinja
    Assembly Version: 0.7.8391.21578
    Win32 Version: 0.7.8391.21578
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/GeoTagNinja.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.1.0.1480
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/NLog.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9115.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.117.0
    Win32 Version: 1.0.117.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
CsvHelper
    Assembly Version: 30.0.0.0
    Win32 Version: 30.0.1.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/CsvHelper.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------

```

**Comment by nemethviktor** [comment]
I'll have a look - what culture setting do you use (language/locale that is)? It's generally easier for me to install a virtual Windows of the same setup as users have than to just modify the date and time format.

**Comment by nemethviktor** [comment]
Hmmm tried in Win10 Home FIN but it looks okay to me
![image](https://user-images.githubusercontent.com/58767235/211425529-7cfbe83f-368b-463e-89df-388c27df2ad5.png)

Admittedly I don't think it would make any difference but can you try the development version please at https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link if it's any better?

Alternatively let me know what version of Windows you're using if it's not W10Home/FIN?
Also possibly share an image that's causing the issue? (not a screenshot but the photo that is being naughty?)
Thanks

**Comment by lintujuh** [comment]
You guessed right, I'm living in Finland. I have Win11 Enterprise, 22H2, English UI, and modified locale.
![image](https://user-images.githubusercontent.com/5797282/211466090-3e7ab94e-a6c2-4bd2-80d8-108d91d2f05f.png)

Your development version didn't work any better, like you assumed.

I had one image in my Pictures folder, rest were folders. When I removed the image, the application started without errors. The conflicting image is attached. [PA021693.zip](https://github.com/nemethviktor/GeoTagNinja/files/10379021/PA021693.zip)

**Comment by nemethviktor** [comment]
Thanks, I'll have a look. The code works out the `date` (from a `string`) at the moment in a somewhat arbitrary way, which doesn't account for all possibilities as I just assumed after testing on 4-5 locales it'd be ok but I think there are smarter ways around it, will dig a little and come back with something useful for you.

**Comment by nemethviktor** [comment]
Same link as previously have another try pls.
I played around with a modified bit of code, I think it works now.

**Comment by lintujuh** [comment]
Now it works. Thank you.
