### ISSUE TITLE
Exception when trying to select time zone in GPX import dialog

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#75]
**Describe the bug**
Unhandled exception dialog pops when trying to select a different time zone.
![image](https://user-images.githubusercontent.com/5797282/224481380-d1a647e9-b179-4bad-a160-dc6370360bf8.png)

**To Reproduce**
1.Open import GPX/JSON File dialog
2. Tick Use this time zone
3. Click on the drop down

Using the a different time zone works without problems if I ignore the error and select Continue in the dialog.

**Expected behavior**
No error message

**Screenshots**
The error text in the dialog is
```
************** Exception Text **************
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GeoTagNinja.FrmImportGpx.updatelbl_TZValue()
   at GeoTagNinja.FrmImportGpx.ckb_UseTimeZone_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GeoTagNinja
    Assembly Version: 0.8.8436.22440
    Win32 Version: 0.8.8436.22440
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/GeoTagNinja.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.1.0.1480
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/NLog.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
CsvHelper
    Assembly Version: 30.0.0.0
    Win32 Version: 30.0.1.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/CsvHelper.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.117.0
    Win32 Version: 1.0.117.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
TimeZoneConverter
    Assembly Version: 6.0.1.0
    Win32 Version: 6.0.1.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/TimeZoneConverter.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
```
**Desktop (please complete the following information):**
 - OS: Win11 Enterprise 22H2
 - Language/Culture: en-FI

**Comment by nemethviktor** [comment]
Noted -- need to head out now though. Will have a proper look on Monday most likely - I tested that functionality in just about all my VMs exc for the Finnish and ofc it's there where it's misbehaving. Sorry :/

**Comment by lintujuh** [comment]
Fixed
